arrowParens: avoid
bracketSameLine: true
bracketSpacing: true
endOfLine: lf
htmlWhitespaceSensitivity: css
jsxSingleQuote: false
printWidth: 120
proseWrap: always
quoteProps: as-needed
semi: true
singleQuote: true
trailingComma: es5
tabWidth: 2
useTabs: false
